import { MigrationInterface, QueryRunner } from "typeorm";

export class SchemaFixes1776339681026 implements MigrationInterface {
    name = 'SchemaFixes1776339681026'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "tasks_owner_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "activity_logs_inventory_item_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "activity_logs_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "inventory_location_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "inventory_last_scanned_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP CONSTRAINT "device_alerts_device_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP CONSTRAINT "device_alerts_acknowledged_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP CONSTRAINT "camera_captures_device_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP CONSTRAINT "camera_captures_location_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "devices_location_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP CONSTRAINT "scan_history_inventory_item_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP CONSTRAINT "scan_history_device_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP CONSTRAINT "scan_history_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."ix_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."ix_locations_name"`);
        await queryRunner.query(`DROP INDEX "public"."ix_locations_code"`);
        await queryRunner.query(`DROP INDEX "public"."ix_inventory_name"`);
        await queryRunner.query(`DROP INDEX "public"."ix_inventory_barcode"`);
        await queryRunner.query(`DROP INDEX "public"."ix_devices_name"`);
        await queryRunner.query(`DROP INDEX "public"."ix_devices_serial_number"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "user"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "location_id"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "configuration"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "completed" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TYPE "public"."userrole" RENAME TO "userrole_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'operator', 'viewer')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'viewer'`);
        await queryRunner.query(`DROP TYPE "public"."userrole_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'viewer'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "UQ_1c65ef243169e51b514c814eeae" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "floor"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "floor" character varying`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "zone"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "zone" character varying`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "capacity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "capacity" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "current_items" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "current_items" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "coordinates"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "coordinates" jsonb`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "is_active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "inventory_item_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "action" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."actiontype" RENAME TO "actiontype_old"`);
        await queryRunner.query(`CREATE TYPE "public"."activity_logs_action_type_enum" AS ENUM('CREATE', 'UPDATE', 'DELETE', 'SCAN', 'ALERT', 'MOVE', 'CHECK')`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "action_type" TYPE "public"."activity_logs_action_type_enum" USING "action_type"::"text"::"public"."activity_logs_action_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."actiontype_old"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "action_type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "location" character varying`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "has_barcode_scan" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "has_barcode_scan" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "is_alert" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "is_alert" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "details"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "details" jsonb`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "inventory_sku_key"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "sku" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "UQ_c33f32cdf6993fe3852073b0d56" UNIQUE ("sku")`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "barcode"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "barcode" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "qr_code"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "qr_code" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "category" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "location_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."inventorystatus" RENAME TO "inventorystatus_old"`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_status_enum" AS ENUM('TERSEDIA', 'DIPERBARUI', 'BERPINDAH', 'HILANG')`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "status" TYPE "public"."inventory_status_enum" USING "status"::"text"::"public"."inventory_status_enum"`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "status" SET DEFAULT 'TERSEDIA'`);
        await queryRunner.query(`DROP TYPE "public"."inventorystatus_old"`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "status" SET DEFAULT 'TERSEDIA'`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "quantity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "quantity" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "min_quantity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "min_quantity" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "max_quantity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "max_quantity" SET DEFAULT '100'`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "unit"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "unit" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "price" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "last_scanned_at"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "last_scanned_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "last_scanned_by"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "last_scanned_by" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TYPE "public"."alerttype" RENAME TO "alerttype_old"`);
        await queryRunner.query(`CREATE TYPE "public"."device_alerts_alert_type_enum" AS ENUM('MOTION', 'TEMPERATURE', 'HUMIDITY', 'UNAUTHORIZED', 'LOW_STOCK', 'DEVICE_OFFLINE', 'CUSTOM')`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "alert_type" TYPE "public"."device_alerts_alert_type_enum" USING "alert_type"::"text"::"public"."device_alerts_alert_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alerttype_old"`);
        await queryRunner.query(`ALTER TYPE "public"."alertseverity" RENAME TO "alertseverity_old"`);
        await queryRunner.query(`CREATE TYPE "public"."device_alerts_severity_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "severity" TYPE "public"."device_alerts_severity_enum" USING "severity"::"text"::"public"."device_alerts_severity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alertseverity_old"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "message"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "message" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "data"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "data" jsonb`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "is_acknowledged" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "is_acknowledged" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "acknowledged_by"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "acknowledged_by" character varying`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "acknowledged_at"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "acknowledged_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "is_resolved" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "is_resolved" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "resolved_at"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "resolved_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "device_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "thumbnail_url"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "thumbnail_url" character varying`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "title" character varying`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "location_name"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "location_name" character varying`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "detected_objects"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "detected_objects" jsonb`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "detected_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "detected_count" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "is_alert" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "is_alert" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "alert_type"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "alert_type" character varying`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "is_reviewed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "is_reviewed" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "reviewed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "reviewed_at"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "reviewed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "captured_at"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "captured_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."devicetype" RENAME TO "devicetype_old"`);
        await queryRunner.query(`CREATE TYPE "public"."devices_device_type_enum" AS ENUM('SCANNER', 'SENSOR', 'CAMERA', 'GATEWAY')`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "device_type" TYPE "public"."devices_device_type_enum" USING "device_type"::"text"::"public"."devices_device_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."devicetype_old"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "serial_number"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "serial_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "UQ_cc9e89897e336172fd06367735d" UNIQUE ("serial_number")`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "devices_api_key_key"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "api_key"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "api_key" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "UQ_4432e06207d18c2e7cc8e45cd58" UNIQUE ("api_key")`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "location" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."devicestatus" RENAME TO "devicestatus_old"`);
        await queryRunner.query(`CREATE TYPE "public"."devices_status_enum" AS ENUM('ONLINE', 'OFFLINE', 'WARNING')`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "status" TYPE "public"."devices_status_enum" USING "status"::"text"::"public"."devices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "status" SET DEFAULT 'OFFLINE'`);
        await queryRunner.query(`DROP TYPE "public"."devicestatus_old"`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "status" SET DEFAULT 'OFFLINE'`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "last_heartbeat"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "last_heartbeat" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "firmware_version"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "firmware_version" character varying`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "ip_address" character varying`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "mac_address"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "mac_address" character varying`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "is_active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "scan_history" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "scan_history" ALTER COLUMN "inventory_item_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP COLUMN "scan_type"`);
        await queryRunner.query(`CREATE TYPE "public"."scan_history_scan_type_enum" AS ENUM('BARCODE', 'QR_CODE', 'RFID', 'MANUAL')`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD "scan_type" "public"."scan_history_scan_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP COLUMN "scanned_data"`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD "scanned_data" character varying`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD "location" character varying`);
        await queryRunner.query(`ALTER TABLE "scan_history" ALTER COLUMN "is_successful" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scan_history" ALTER COLUMN "is_successful" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP COLUMN "error_message"`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD "error_message" character varying`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_0631c1eb8316f8af361cf14eb85" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_70d0424397892fd3541220f85c8" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_d54f841fa5478e4734590d44036" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_1eea99c8c645d7541002473a015" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD CONSTRAINT "FK_80f73a4b3b7005a129d785971ee" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD CONSTRAINT "FK_aa39eff145b3a960667fb061a03" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD CONSTRAINT "FK_19108bf40802e9a6c6bb2555253" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD CONSTRAINT "FK_a11842a13a9ddb9da861bb40bcf" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD CONSTRAINT "FK_584cdafc654ce0eef36e6eda3ef" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD CONSTRAINT "FK_bc0f65ccfc3b035ede067408772" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD CONSTRAINT "FK_dc4e9fe64c4e79bf06775fcc985" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "scan_history" DROP CONSTRAINT "FK_dc4e9fe64c4e79bf06775fcc985"`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP CONSTRAINT "FK_bc0f65ccfc3b035ede067408772"`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP CONSTRAINT "FK_584cdafc654ce0eef36e6eda3ef"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP CONSTRAINT "FK_a11842a13a9ddb9da861bb40bcf"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP CONSTRAINT "FK_19108bf40802e9a6c6bb2555253"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP CONSTRAINT "FK_aa39eff145b3a960667fb061a03"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP CONSTRAINT "FK_80f73a4b3b7005a129d785971ee"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_1eea99c8c645d7541002473a015"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_d54f841fa5478e4734590d44036"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_70d0424397892fd3541220f85c8"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_0631c1eb8316f8af361cf14eb85"`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP COLUMN "error_message"`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD "error_message" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "scan_history" ALTER COLUMN "is_successful" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "scan_history" ALTER COLUMN "is_successful" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD "location" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP COLUMN "scanned_data"`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD "scanned_data" character varying(500) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scan_history" DROP COLUMN "scan_type"`);
        await queryRunner.query(`DROP TYPE "public"."scan_history_scan_type_enum"`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD "scan_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "scan_history" ALTER COLUMN "inventory_item_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "scan_history" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "is_active" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "mac_address"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "mac_address" character varying(17)`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "ip_address" character varying(45)`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "firmware_version"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "firmware_version" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "last_heartbeat"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "last_heartbeat" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."devicestatus_old" AS ENUM('ONLINE', 'OFFLINE', 'WARNING')`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "status" TYPE "public"."devicestatus_old" USING "status"::"text"::"public"."devicestatus_old"`);
        await queryRunner.query(`DROP TYPE "public"."devices_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."devicestatus_old" RENAME TO "devicestatus"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "location" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "UQ_4432e06207d18c2e7cc8e45cd58"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "api_key"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "api_key" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "devices_api_key_key" UNIQUE ("api_key")`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "UQ_cc9e89897e336172fd06367735d"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "serial_number"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "serial_number" character varying(100) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."devicetype_old" AS ENUM('SCANNER', 'SENSOR', 'CAMERA', 'GATEWAY')`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "device_type" TYPE "public"."devicetype_old" USING "device_type"::"text"::"public"."devicetype_old"`);
        await queryRunner.query(`DROP TYPE "public"."devices_device_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."devicetype_old" RENAME TO "devicetype"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "devices" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "captured_at"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "captured_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "reviewed_at"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "reviewed_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "reviewed_by" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "is_reviewed" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "is_reviewed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "alert_type"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "alert_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "is_alert" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "is_alert" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "detected_count" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "detected_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "detected_objects"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "detected_objects" text`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "location_name"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "location_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "title" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "thumbnail_url"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "thumbnail_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "camera_captures" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD "image_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "device_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "resolved_at"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "resolved_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "is_resolved" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "is_resolved" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "acknowledged_at"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "acknowledged_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "acknowledged_by"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "acknowledged_by" uuid`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "is_acknowledged" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "is_acknowledged" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "data"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "data" text`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "message"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "message" text`);
        await queryRunner.query(`ALTER TABLE "device_alerts" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD "title" character varying(200) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."alertseverity_old" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "severity" TYPE "public"."alertseverity_old" USING "severity"::"text"::"public"."alertseverity_old"`);
        await queryRunner.query(`DROP TYPE "public"."device_alerts_severity_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."alertseverity_old" RENAME TO "alertseverity"`);
        await queryRunner.query(`CREATE TYPE "public"."alerttype_old" AS ENUM('MOTION', 'TEMPERATURE', 'HUMIDITY', 'UNAUTHORIZED', 'LOW_STOCK', 'DEVICE_OFFLINE', 'CUSTOM')`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "alert_type" TYPE "public"."alerttype_old" USING "alert_type"::"text"::"public"."alerttype_old"`);
        await queryRunner.query(`DROP TYPE "public"."device_alerts_alert_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."alerttype_old" RENAME TO "alerttype"`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "last_scanned_by"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "last_scanned_by" uuid`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "last_scanned_at"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "last_scanned_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "image_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "price" TYPE numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "unit"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "unit" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "max_quantity" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "max_quantity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "min_quantity" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "min_quantity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "quantity" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "quantity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."inventorystatus_old" AS ENUM('Tersedia', 'Diperbarui', 'Berpindah', 'Hilang')`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "status" TYPE "public"."inventorystatus_old" USING "status"::"text"::"public"."inventorystatus_old"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."inventorystatus_old" RENAME TO "inventorystatus"`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "location_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "category" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "qr_code"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "qr_code" text`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "barcode"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "barcode" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "UQ_c33f32cdf6993fe3852073b0d56"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "sku" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "inventory_sku_key" UNIQUE ("sku")`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "details"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "details" text`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "is_alert" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "is_alert" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "has_barcode_scan" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "has_barcode_scan" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "location" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "action_type" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."actiontype_old" AS ENUM('CREATED', 'UPDATED', 'DELETED', 'SCANNED', 'MOVED', 'BORROWED', 'RETURNED', 'ALERT', 'LOGIN', 'LOGOUT')`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "action_type" TYPE "public"."actiontype_old" USING "action_type"::"text"::"public"."actiontype_old"`);
        await queryRunner.query(`DROP TYPE "public"."activity_logs_action_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."actiontype_old" RENAME TO "actiontype"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "action" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "inventory_item_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "is_active" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "coordinates"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "coordinates" json`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "current_items" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "current_items" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "capacity" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "capacity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "zone"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "zone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "floor"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "floor" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "UQ_1c65ef243169e51b514c814eeae"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."userrole_old" AS ENUM('admin', 'operator', 'viewer')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."userrole_old" USING "role"::"text"::"public"."userrole_old"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."userrole_old" RENAME TO "userrole"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "completed" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "configuration" text`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "location_id" uuid`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "location" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD "user" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ix_devices_serial_number" ON "devices" ("serial_number") `);
        await queryRunner.query(`CREATE INDEX "ix_devices_name" ON "devices" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ix_inventory_barcode" ON "inventory" ("barcode") `);
        await queryRunner.query(`CREATE INDEX "ix_inventory_name" ON "inventory" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ix_locations_code" ON "locations" ("code") `);
        await queryRunner.query(`CREATE INDEX "ix_locations_name" ON "locations" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ix_users_email" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD CONSTRAINT "scan_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD CONSTRAINT "scan_history_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scan_history" ADD CONSTRAINT "scan_history_inventory_item_id_fkey" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "devices_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD CONSTRAINT "camera_captures_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "camera_captures" ADD CONSTRAINT "camera_captures_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD CONSTRAINT "device_alerts_acknowledged_by_fkey" FOREIGN KEY ("acknowledged_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_alerts" ADD CONSTRAINT "device_alerts_device_id_fkey" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "inventory_last_scanned_by_fkey" FOREIGN KEY ("last_scanned_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "inventory_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "activity_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "activity_logs_inventory_item_id_fkey" FOREIGN KEY ("inventory_item_id") REFERENCES "inventory"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "tasks_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
